/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parkingmvc.vistas;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import javax.swing.JOptionPane;
import parkingmvc.controladores.ControladorConsultaCliente;
import parkingmvc.controladores.ControladorConsultaParqueadero;
import parkingmvc.controladores.ControladorSalidaVehiculo;
import parkingmvc.modelos.FixedSizeDocument;
import parkingmvc.modelos.ModeloCliente;
import parkingmvc.modelos.ModeloParqueadero;
import parkingmvc.modelos.ModeloVehiculo;

/**
 *
 * @author aoroz
 */
public class VistaHome extends javax.swing.JFrame {
        
    int xMouse, yMouse;
    
    public VistaHome() {
        initComponents();        
        fieldSalida.setDocument(new FixedSizeDocument(6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelNavigation = new javax.swing.JPanel();
        btnVehiculo = new javax.swing.JPanel();
        btnVehiculoLabel = new javax.swing.JLabel();
        btnCliente = new javax.swing.JPanel();
        btnClienteLabel = new javax.swing.JLabel();
        btnTarifa = new javax.swing.JPanel();
        btnTarifaLabel = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JPanel();
        btnConsultaLabel = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        btnCloseLabel = new javax.swing.JLabel();
        btnHome = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        panelInfo = new javax.swing.JPanel();
        labelInfoOcupados = new javax.swing.JLabel();
        labelOcupados = new javax.swing.JLabel();
        labelinfoDisponibles = new javax.swing.JLabel();
        labelDisponibles = new javax.swing.JLabel();
        labelInfohora = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelInfotiempo = new javax.swing.JLabel();
        labelTiempo = new javax.swing.JLabel();
        labelInfoplaca = new javax.swing.JLabel();
        labelPlaca = new javax.swing.JLabel();
        labelInfocobro = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        separador3 = new javax.swing.JSeparator();
        labelInfo = new javax.swing.JLabel();
        labelInfo1 = new javax.swing.JLabel();
        labelIngresarplaca = new javax.swing.JLabel();
        labelSalida = new javax.swing.JLabel();
        labelDescripcionsalida = new javax.swing.JLabel();
        fieldSalida = new javax.swing.JTextField();
        separador2 = new javax.swing.JSeparator();
        btnSalidaPlaca = new javax.swing.JButton();
        btnDisponibilidad = new javax.swing.JButton();
        labelResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("frameHome"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelNavigation.setBackground(new java.awt.Color(56, 61, 69));
        panelNavigation.setMaximumSize(new java.awt.Dimension(800, 60));
        panelNavigation.setMinimumSize(new java.awt.Dimension(800, 60));
        panelNavigation.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelNavigationMouseDragged(evt);
            }
        });
        panelNavigation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelNavigationMousePressed(evt);
            }
        });

        btnVehiculo.setBackground(new java.awt.Color(56, 61, 69));
        btnVehiculo.setMaximumSize(new java.awt.Dimension(120, 60));

        btnVehiculoLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVehiculoLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVehiculoLabel.setText("Vehiculo");
        btnVehiculoLabel.setAlignmentY(0.0F);
        btnVehiculoLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVehiculoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculoLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculoLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculoLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVehiculoLayout = new javax.swing.GroupLayout(btnVehiculo);
        btnVehiculo.setLayout(btnVehiculoLayout);
        btnVehiculoLayout.setHorizontalGroup(
            btnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnVehiculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVehiculoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVehiculoLayout.setVerticalGroup(
            btnVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVehiculoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnCliente.setBackground(new java.awt.Color(56, 61, 69));
        btnCliente.setMaximumSize(new java.awt.Dimension(120, 60));

        btnClienteLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnClienteLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnClienteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnClienteLabel.setText("Cliente");
        btnClienteLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnClienteLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClienteLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnClienteLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnClienteLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnClienteLayout = new javax.swing.GroupLayout(btnCliente);
        btnCliente.setLayout(btnClienteLayout);
        btnClienteLayout.setHorizontalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnClienteLayout.setVerticalGroup(
            btnClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClienteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnTarifa.setBackground(new java.awt.Color(56, 61, 69));
        btnTarifa.setMaximumSize(new java.awt.Dimension(120, 60));

        btnTarifaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTarifaLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnTarifaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTarifaLabel.setText("Parqueadero");
        btnTarifaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTarifaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTarifaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTarifaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTarifaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnTarifaLayout = new javax.swing.GroupLayout(btnTarifa);
        btnTarifa.setLayout(btnTarifaLayout);
        btnTarifaLayout.setHorizontalGroup(
            btnTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTarifaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTarifaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnTarifaLayout.setVerticalGroup(
            btnTarifaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnTarifaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnConsulta.setBackground(new java.awt.Color(56, 61, 69));
        btnConsulta.setMaximumSize(new java.awt.Dimension(120, 60));

        btnConsultaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConsultaLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnConsultaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConsultaLabel.setText("Consulta");
        btnConsultaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnConsultaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsultaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnConsultaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnConsultaLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnConsultaLayout = new javax.swing.GroupLayout(btnConsulta);
        btnConsulta.setLayout(btnConsultaLayout);
        btnConsultaLayout.setHorizontalGroup(
            btnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnConsultaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnConsultaLayout.setVerticalGroup(
            btnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConsultaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnClose.setBackground(new java.awt.Color(33, 40, 48));
        btnClose.setMaximumSize(new java.awt.Dimension(60, 60));
        btnClose.setMinimumSize(new java.awt.Dimension(60, 60));
        btnClose.setPreferredSize(new java.awt.Dimension(45, 60));

        btnCloseLabel.setBackground(new java.awt.Color(33, 40, 48));
        btnCloseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseLabel.setText("X");
        btnCloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCloseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        btnHome.setBackground(new java.awt.Color(33, 40, 48));

        labelLogo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelLogo.setForeground(new java.awt.Color(255, 255, 255));
        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/car-park-white.png"))); // NOI18N
        labelLogo.setText("ParkIng MVC");
        labelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        labelLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelLogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelLogoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnHomeLayout = new javax.swing.GroupLayout(btnHome);
        btnHome.setLayout(btnHomeLayout);
        btnHomeLayout.setHorizontalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnHomeLayout.setVerticalGroup(
            btnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHomeLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout panelNavigationLayout = new javax.swing.GroupLayout(panelNavigation);
        panelNavigation.setLayout(panelNavigationLayout);
        panelNavigationLayout.setHorizontalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(btnVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        panelNavigationLayout.setVerticalGroup(
            panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigationLayout.createSequentialGroup()
                .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelNavigationLayout.createSequentialGroup()
                        .addGroup(panelNavigationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(panelNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        panelInfo.setBackground(new java.awt.Color(237, 237, 237));

        labelInfoOcupados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoOcupados.setForeground(new java.awt.Color(56, 61, 69));
        labelInfoOcupados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfoOcupados.setText("Puestos ocupados");

        labelOcupados.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelOcupados.setForeground(new java.awt.Color(0, 174, 181));
        labelOcupados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelOcupados.setText(" ");

        labelinfoDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelinfoDisponibles.setForeground(new java.awt.Color(56, 61, 69));
        labelinfoDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelinfoDisponibles.setText("Puestos disponibles");

        labelDisponibles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDisponibles.setForeground(new java.awt.Color(0, 174, 181));
        labelDisponibles.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDisponibles.setText(" ");

        labelInfohora.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfohora.setForeground(new java.awt.Color(56, 61, 69));
        labelInfohora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfohora.setText("Hora de ingreso / salida");

        labelHora.setForeground(new java.awt.Color(153, 153, 153));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHora.setText(" ");

        labelInfotiempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfotiempo.setForeground(new java.awt.Color(56, 61, 69));
        labelInfotiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfotiempo.setText("Tiempo en el parqueadero");

        labelTiempo.setForeground(new java.awt.Color(153, 153, 153));
        labelTiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTiempo.setText(" ");

        labelInfoplaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfoplaca.setForeground(new java.awt.Color(56, 61, 69));
        labelInfoplaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfoplaca.setText("Placa");

        labelPlaca.setBackground(new java.awt.Color(51, 0, 204));
        labelPlaca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelPlaca.setForeground(new java.awt.Color(0, 174, 181));
        labelPlaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPlaca.setText(" ");

        labelInfocobro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInfocobro.setForeground(new java.awt.Color(56, 61, 69));
        labelInfocobro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfocobro.setText("Total a pagar");

        labelTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelTotal.setForeground(new java.awt.Color(0, 174, 181));
        labelTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTotal.setText(" ");

        separador3.setBackground(new java.awt.Color(204, 204, 204));
        separador3.setForeground(new java.awt.Color(204, 204, 204));

        labelInfo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelInfo.setForeground(new java.awt.Color(153, 153, 153));
        labelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo.setText("Información puestos disponibles");

        labelInfo1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelInfo1.setForeground(new java.awt.Color(153, 153, 153));
        labelInfo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInfo1.setText("Información pago");

        javax.swing.GroupLayout panelInfoLayout = new javax.swing.GroupLayout(panelInfo);
        panelInfo.setLayout(panelInfoLayout);
        panelInfoLayout.setHorizontalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(labelInfoOcupados, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelinfoDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelDisponibles, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelOcupados, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelInfohora, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelHora, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelInfotiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelInfoplaca, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelInfocobro, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                        .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelInfoLayout.setVerticalGroup(
            panelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelinfoDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelDisponibles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfoOcupados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelOcupados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(separador3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfoplaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPlaca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfocobro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInfohora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelInfotiempo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTiempo)
                .addGap(43, 43, 43))
        );

        jPanel1.add(panelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 260, 440));

        labelIngresarplaca.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelIngresarplaca.setForeground(new java.awt.Color(33, 40, 48));
        labelIngresarplaca.setText("Información del parqueadero");
        jPanel1.add(labelIngresarplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        labelSalida.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelSalida.setForeground(new java.awt.Color(33, 40, 48));
        labelSalida.setText("Salida vehículo");
        jPanel1.add(labelSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        labelDescripcionsalida.setForeground(new java.awt.Color(153, 153, 153));
        labelDescripcionsalida.setText("Ingresa la placa para la salida del vehículo");
        jPanel1.add(labelDescripcionsalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, -1, -1));

        fieldSalida.setBackground(new java.awt.Color(237, 237, 237));
        fieldSalida.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldSalida.setForeground(new java.awt.Color(153, 153, 153));
        fieldSalida.setBorder(null);
        fieldSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldSalidaKeyTyped(evt);
            }
        });
        jPanel1.add(fieldSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 300, 30));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 300, 20));

        btnSalidaPlaca.setBackground(new java.awt.Color(33, 40, 48));
        btnSalidaPlaca.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSalidaPlaca.setForeground(new java.awt.Color(255, 255, 255));
        btnSalidaPlaca.setText("Salida");
        btnSalidaPlaca.setBorder(null);
        jPanel1.add(btnSalidaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 150, 35));

        btnDisponibilidad.setBackground(new java.awt.Color(153, 153, 153));
        btnDisponibilidad.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnDisponibilidad.setForeground(new java.awt.Color(255, 255, 255));
        btnDisponibilidad.setText("Disponibilidad");
        btnDisponibilidad.setBorder(null);
        jPanel1.add(btnDisponibilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 140, 35));

        labelResultado.setForeground(new java.awt.Color(0, 174, 181));
        labelResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultado.setText(" ");
        jPanel1.add(labelResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 300, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void labelLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseClicked
        VistaHome abrir = new VistaHome();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
        
        ModeloCliente modeloCliente = new ModeloCliente();
        ModeloVehiculo modeloVehiculo = new ModeloVehiculo();
        ModeloParqueadero modeloParqueadero = new ModeloParqueadero();
        ControladorSalidaVehiculo controladorSalidaVehiculo = new ControladorSalidaVehiculo(abrir, modeloCliente, modeloVehiculo);
        ControladorConsultaParqueadero controladorConsultaParqueadero = new ControladorConsultaParqueadero(abrir, modeloParqueadero);
    }//GEN-LAST:event_labelLogoMouseClicked

    private void labelLogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseEntered
        btnHome.setBackground(Color.decode("#00AEB5"));
    }//GEN-LAST:event_labelLogoMouseEntered

    private void btnVehiculoLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculoLabelMouseClicked
        VistaVehiculo abrir = new VistaVehiculo();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVehiculoLabelMouseClicked

    private void btnVehiculoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculoLabelMouseEntered
        btnVehiculo.setBackground(Color.decode("#00AEB5"));
    }//GEN-LAST:event_btnVehiculoLabelMouseEntered

    private void btnVehiculoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculoLabelMouseExited
        btnVehiculo.setBackground(Color.decode("#383D45"));
    }//GEN-LAST:event_btnVehiculoLabelMouseExited

    private void btnClienteLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLabelMouseClicked
        VistaCliente abrir = new VistaCliente();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClienteLabelMouseClicked

    private void btnClienteLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLabelMouseEntered
        btnCliente.setBackground(Color.decode("#00AEB5"));
    }//GEN-LAST:event_btnClienteLabelMouseEntered

    private void btnClienteLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClienteLabelMouseExited
        btnCliente.setBackground(Color.decode("#383D45"));
    }//GEN-LAST:event_btnClienteLabelMouseExited

    private void btnTarifaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLabelMouseClicked
        VistaParqueadero abrir = new VistaParqueadero();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTarifaLabelMouseClicked

    private void btnTarifaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLabelMouseEntered
        btnTarifa.setBackground(Color.decode("#00AEB5"));
    }//GEN-LAST:event_btnTarifaLabelMouseEntered

    private void btnTarifaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTarifaLabelMouseExited
        btnTarifa.setBackground(Color.decode("#383D45"));
    }//GEN-LAST:event_btnTarifaLabelMouseExited

    private void btnConsultaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLabelMouseClicked
        VistaConsulta abrir = new VistaConsulta();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnConsultaLabelMouseClicked

    private void btnConsultaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLabelMouseEntered
        btnConsulta.setBackground(Color.decode("#00AEB5"));
    }//GEN-LAST:event_btnConsultaLabelMouseEntered

    private void btnConsultaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsultaLabelMouseExited
        btnConsulta.setBackground(Color.decode("#383D45"));
    }//GEN-LAST:event_btnConsultaLabelMouseExited

    private void btnCloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseLabelMouseClicked

    private void btnCloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseEntered
        // Hover
        btnClose.setBackground(Color.RED);
    }//GEN-LAST:event_btnCloseLabelMouseEntered

    private void btnCloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseExited
        // Unhover
        btnClose.setBackground(Color.decode("#212830"));
    }//GEN-LAST:event_btnCloseLabelMouseExited

    private void panelNavigationMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNavigationMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        // Ubicación de la ventana
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelNavigationMouseDragged

    private void panelNavigationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNavigationMousePressed
        // Ubicación del puntero
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelNavigationMousePressed

    private void labelLogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoMouseExited
        btnHome.setBackground(Color.decode("#212830"));
    }//GEN-LAST:event_labelLogoMouseExited

    private void fieldSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldSalidaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'0' || c>'9') && (c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_BACKSPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldSalidaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCliente;
    public javax.swing.JLabel btnClienteLabel;
    private javax.swing.JPanel btnClose;
    public javax.swing.JLabel btnCloseLabel;
    private javax.swing.JPanel btnConsulta;
    public javax.swing.JLabel btnConsultaLabel;
    public javax.swing.JButton btnDisponibilidad;
    private javax.swing.JPanel btnHome;
    public javax.swing.JButton btnSalidaPlaca;
    private javax.swing.JPanel btnTarifa;
    public javax.swing.JLabel btnTarifaLabel;
    private javax.swing.JPanel btnVehiculo;
    public javax.swing.JLabel btnVehiculoLabel;
    public javax.swing.JTextField fieldSalida;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescripcionsalida;
    public javax.swing.JLabel labelDisponibles;
    public javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelInfo1;
    private javax.swing.JLabel labelInfoOcupados;
    private javax.swing.JLabel labelInfocobro;
    private javax.swing.JLabel labelInfohora;
    private javax.swing.JLabel labelInfoplaca;
    private javax.swing.JLabel labelInfotiempo;
    private javax.swing.JLabel labelIngresarplaca;
    public javax.swing.JLabel labelLogo;
    public javax.swing.JLabel labelOcupados;
    public javax.swing.JLabel labelPlaca;
    public javax.swing.JLabel labelResultado;
    private javax.swing.JLabel labelSalida;
    public javax.swing.JLabel labelTiempo;
    public javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelinfoDisponibles;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelNavigation;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    // End of variables declaration//GEN-END:variables
}
