/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkingmvc.vistas;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import parkingmvc.modelos.FixedSizeDocument;

/**
 *
 * @author Alejandro
 */
public class VistaRegistroVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form VistaRegistroVehículo
     */
    
    /* Coordenadas del puntero */
    int xMouse, yMouse;
    
    public VistaRegistroVehiculo() {
        initComponents();
        this.setLocationRelativeTo(null);
        fieldIngresoplaca.setDocument(new FixedSizeDocument(6));
        fieldIngresomarca.setDocument(new FixedSizeDocument(45));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelVehiculo = new javax.swing.JLabel();
        labelDescripcion = new javax.swing.JLabel();
        labelIngresaPlaca = new javax.swing.JLabel();
        labelIngresaMarca = new javax.swing.JLabel();
        fieldIngresoplaca = new javax.swing.JTextField();
        fieldIngresomarca = new javax.swing.JTextField();
        separador4 = new javax.swing.JSeparator();
        separador2 = new javax.swing.JSeparator();
        labelIngresaColor = new javax.swing.JLabel();
        labelIngresaModelo = new javax.swing.JLabel();
        fieldIngresocolor = new javax.swing.JTextField();
        fieldIngresomodelo = new javax.swing.JTextField();
        separador1 = new javax.swing.JSeparator();
        separador3 = new javax.swing.JSeparator();
        labelResultadovehiculo = new javax.swing.JLabel();
        btnVolver = new javax.swing.JPanel();
        btnVolverLabel = new javax.swing.JLabel();
        panelNavigation1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JPanel();
        btnCloseLabel = new javax.swing.JLabel();
        btnRegistrarVehiculo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("frameRegistroVehiculo"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelVehiculo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelVehiculo.setForeground(new java.awt.Color(33, 40, 48));
        labelVehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelVehiculo.setText("Registrar vehículo");
        jPanel1.add(labelVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 620, -1));

        labelDescripcion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        labelDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        labelDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDescripcion.setText("Por favor ingresa la información completa del vehículo");
        jPanel1.add(labelDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 620, -1));

        labelIngresaPlaca.setForeground(new java.awt.Color(153, 153, 153));
        labelIngresaPlaca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIngresaPlaca.setText("Número de Placa");
        jPanel1.add(labelIngresaPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 300, -1));

        labelIngresaMarca.setForeground(new java.awt.Color(153, 153, 153));
        labelIngresaMarca.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIngresaMarca.setText("Marca");
        jPanel1.add(labelIngresaMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 300, -1));

        fieldIngresoplaca.setBackground(new java.awt.Color(237, 237, 237));
        fieldIngresoplaca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldIngresoplaca.setForeground(new java.awt.Color(153, 153, 153));
        fieldIngresoplaca.setBorder(null);
        fieldIngresoplaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIngresoplacaKeyTyped(evt);
            }
        });
        jPanel1.add(fieldIngresoplaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 300, 30));

        fieldIngresomarca.setBackground(new java.awt.Color(237, 237, 237));
        fieldIngresomarca.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldIngresomarca.setForeground(new java.awt.Color(153, 153, 153));
        fieldIngresomarca.setBorder(null);
        fieldIngresomarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldIngresomarcaKeyTyped(evt);
            }
        });
        jPanel1.add(fieldIngresomarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 300, 30));
        jPanel1.add(separador4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 300, 20));
        jPanel1.add(separador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 300, 20));

        labelIngresaColor.setForeground(new java.awt.Color(153, 153, 153));
        labelIngresaColor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIngresaColor.setText("Color del vehículo");
        jPanel1.add(labelIngresaColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 300, -1));

        labelIngresaModelo.setForeground(new java.awt.Color(153, 153, 153));
        labelIngresaModelo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelIngresaModelo.setText("Modelo");
        jPanel1.add(labelIngresaModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 300, -1));

        fieldIngresocolor.setBackground(new java.awt.Color(237, 237, 237));
        fieldIngresocolor.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldIngresocolor.setForeground(new java.awt.Color(153, 153, 153));
        fieldIngresocolor.setBorder(null);
        jPanel1.add(fieldIngresocolor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 300, 30));

        fieldIngresomodelo.setBackground(new java.awt.Color(237, 237, 237));
        fieldIngresomodelo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        fieldIngresomodelo.setForeground(new java.awt.Color(153, 153, 153));
        fieldIngresomodelo.setBorder(null);
        jPanel1.add(fieldIngresomodelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 300, 30));
        jPanel1.add(separador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 300, 20));
        jPanel1.add(separador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 300, 20));

        labelResultadovehiculo.setForeground(new java.awt.Color(0, 174, 181));
        labelResultadovehiculo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultadovehiculo.setText(" ");
        jPanel1.add(labelResultadovehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, 620, -1));

        btnVolver.setBackground(new java.awt.Color(33, 40, 48));
        btnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnVolverLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolverLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnVolverLabel.setText("Regresar");
        btnVolverLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnVolverLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVolverLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVolverLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVolverLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnVolverLayout = new javax.swing.GroupLayout(btnVolver);
        btnVolver.setLayout(btnVolverLayout);
        btnVolverLayout.setHorizontalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnVolverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVolverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnVolverLayout.setVerticalGroup(
            btnVolverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnVolverLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        panelNavigation1.setBackground(new java.awt.Color(56, 61, 69));
        panelNavigation1.setMaximumSize(new java.awt.Dimension(800, 60));
        panelNavigation1.setOpaque(false);
        panelNavigation1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelNavigation1MouseDragged(evt);
            }
        });
        panelNavigation1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelNavigation1MousePressed(evt);
            }
        });

        btnClose.setBackground(new java.awt.Color(33, 40, 48));
        btnClose.setMaximumSize(new java.awt.Dimension(120, 60));

        btnCloseLabel.setBackground(new java.awt.Color(33, 40, 48));
        btnCloseLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCloseLabel.setForeground(new java.awt.Color(255, 255, 255));
        btnCloseLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCloseLabel.setText("X");
        btnCloseLabel.setAlignmentY(0.0F);
        btnCloseLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCloseLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCloseLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnCloseLayout = new javax.swing.GroupLayout(btnClose);
        btnClose.setLayout(btnCloseLayout);
        btnCloseLayout.setHorizontalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCloseLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(btnCloseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        btnCloseLayout.setVerticalGroup(
            btnCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCloseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNavigation1Layout = new javax.swing.GroupLayout(panelNavigation1);
        panelNavigation1.setLayout(panelNavigation1Layout);
        panelNavigation1Layout.setHorizontalGroup(
            panelNavigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavigation1Layout.createSequentialGroup()
                .addGap(0, 740, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelNavigation1Layout.setVerticalGroup(
            panelNavigation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavigation1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(panelNavigation1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        btnRegistrarVehiculo.setBackground(new java.awt.Color(0, 174, 181));
        btnRegistrarVehiculo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegistrarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarVehiculo.setText("Registrar");
        btnRegistrarVehiculo.setBorder(null);
        jPanel1.add(btnRegistrarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 150, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverLabelMouseClicked
        VistaHome abrir = new VistaHome();
        abrir.setLocationRelativeTo(null);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverLabelMouseClicked

    private void btnVolverLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverLabelMouseEntered
        btnVolver.setBackground(Color.decode("#383D45"));
    }//GEN-LAST:event_btnVolverLabelMouseEntered

    private void btnVolverLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVolverLabelMouseExited
        btnVolver.setBackground(Color.decode("#212830"));
    }//GEN-LAST:event_btnVolverLabelMouseExited

    private void btnCloseLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCloseLabelMouseClicked

    private void btnCloseLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseEntered
        // Hover
        btnClose.setBackground(Color.RED);
    }//GEN-LAST:event_btnCloseLabelMouseEntered

    private void btnCloseLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseLabelMouseExited
        // Unhover
        btnClose.setBackground(Color.decode("#212830"));
    }//GEN-LAST:event_btnCloseLabelMouseExited

    private void panelNavigation1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNavigation1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        // Ubicación de la ventana
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelNavigation1MouseDragged

    private void panelNavigation1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelNavigation1MousePressed
        // Ubicación del puntero
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelNavigation1MousePressed

    private void fieldIngresoplacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIngresoplacaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        if((c<'0' || c>'9') && (c<'a' || c>'z') && (c<'A' || c>'Z') && (c!=(char)KeyEvent.VK_BACKSPACE)){
            evt.consume();
        }
    }//GEN-LAST:event_fieldIngresoplacaKeyTyped

    private void fieldIngresomarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldIngresomarcaKeyTyped
        // TODO add your handling code here:        
    }//GEN-LAST:event_fieldIngresomarcaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaRegistroVehiculo().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnClose;
    public javax.swing.JLabel btnCloseLabel;
    public javax.swing.JButton btnRegistrarVehiculo;
    private javax.swing.JPanel btnVolver;
    public javax.swing.JLabel btnVolverLabel;
    public javax.swing.JTextField fieldIngresocolor;
    public javax.swing.JTextField fieldIngresomarca;
    public javax.swing.JTextField fieldIngresomodelo;
    public javax.swing.JTextField fieldIngresoplaca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelIngresaColor;
    private javax.swing.JLabel labelIngresaMarca;
    private javax.swing.JLabel labelIngresaModelo;
    private javax.swing.JLabel labelIngresaPlaca;
    public javax.swing.JLabel labelResultadovehiculo;
    private javax.swing.JLabel labelVehiculo;
    private javax.swing.JPanel panelNavigation1;
    private javax.swing.JSeparator separador1;
    private javax.swing.JSeparator separador2;
    private javax.swing.JSeparator separador3;
    private javax.swing.JSeparator separador4;
    // End of variables declaration//GEN-END:variables
}
